# Will there be automatic backups
autoBackups: true

# How often the server will automatically backup in minutes
autoBackupFrequency: 1440

backupFolderDirectory: ''

# To include the plugins' jar files
includePluginJars: false

# To include the plugins' jar files
includeServerJar: false

# What folders you dont want backed up
backupFolderExceptions:
  - 'backups'
  - 'cache'
  - 'logs'

# Which file extensions you dont want backed up
backupExtensionExceptions:
  - 'jar'
  - 'bat'

# format that backups will be named. &%date%& will be replaced with the date
backupNameFormat: 'Server-Backup-%date%'

# Format that the date will be presented. For syntax, consult https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
dateFormat: 'yyyy-MM-dd_HH-mm-ss'

# IF you want full player saves that are in that world to be rolled back or not(Location will always be rolled back)
restorePlayerWithWorld: false
