name: TimeMachine
author: Warunek
main: com.github.zwarunek.timemachine.TimeMachine
version: 1.3.1
api-version: 1.13
load: STARTUP
description: An easy and simple server backup solution
commands:
  timemachine:
    aliases: [tm]
    description: command for changing settings and functionality
    usage: /<command> help
